version: '3'
services:

  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - FLASK_APP=main.py  # Defina a variável de ambiente FLASK_APP para o arquivo principal da primeira aplicação
    image: flask-website:app
    ports:
      - "5000:5000"

  flask_api:
    build:
      context: .
      dockerfile: Dockerfile.api
      args:
        - FLASK_APP=main_api.py  # Defina a variável de ambiente FLASK_APP para o arquivo principal da segunda aplicação
    restart: on-failure
    image: flask-website:api
    ports:
      - "6969:6969"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - flask_app
      - flask_api
